name: bunda_care
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^1.2.0
  provider: ^6.0.5
  intl: ^0.20.2
  fl_chart: ^1.1.1
  google_fonts: ^6.2.0
  flutter_dotenv: ^5.0.0
  font_awesome_flutter: ^10.7.0
  
  # HTTP & Networking
  dio: ^5.4.0
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_hive_store: ^3.2.2
  
  # Secure Storage
  flutter_secure_storage: ^9.0.0
  
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  path_provider_linux: ^2.2.1
  
  # Google Sign-In
  google_sign_in: ^6.2.1
  
  # Routing
  go_router: ^14.0.0
  flutter_html: ^3.0.0
  cached_network_image: ^3.4.1
  logger: ^2.6.2
  shimmer: ^3.0.0



dev_dependencies:
  flutter_test:

    sdk: flutter


  flutter_lints: ^6.0.0






flutter:


  uses-material-design: true

  # Daftar aset yang digunakan dalam aplikasi
  assets:
    - .env
    - lib/assets/images/